version: 2.1

orbs:
  node: circleci/node@7.0.0
  slack: circleci/slack@4.4.4
jobs:
  build_and_deploy_mainnet:
    resource_class: large
    docker:
      - image: 'cimg/node:20.19'
    environment:
      DEPLOY_HOST: 34.53.102.108
      DEPLOY_FOLDER: staking-meter-io
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:48o4O3yWCP1MbjxhyGvDL+NNUsYcRJVodZjzg7nV0C4"
      - run:
          name: install rsync
          command: |
            sudo apt-get update 
            sudo apt-get install -y rsync
      - checkout
      - restore_cache:
          key: meter-staking-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: meter-staking-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: production build
          command: VUE_APP_STATUS=mainnet npm run build
      - run:
          name: deploy
          command: |
            rsync -e "ssh $SSH_OPTIONS" -rzvh --delete ./dist/ root@$DEPLOY_HOST:/var/www/$DEPLOY_FOLDER/
            ssh $SSH_OPTIONS root@$DEPLOY_HOST "service nginx restart"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  build_and_deploy_staging:
    resource_class: large
    docker:
      - image: 'cimg/node:16.17'
    environment:
      DEPLOY_HOST: 34.53.102.108
      DEPLOY_FOLDER: staking-meter-io
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:48o4O3yWCP1MbjxhyGvDL+NNUsYcRJVodZjzg7nV0C4"
      - run:
          name: install rsync
          command: |
            sudo apt-get update 
            sudo apt-get install -y rsync
      - checkout
      - restore_cache:
          key: meter-staking-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install
      - save_cache:
          key: meter-staking-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: testnet build
          command: VUE_APP_STATUS=staging npm run build
      - run:
          name: deploy
          command: |
            rsync -e "ssh $SSH_OPTIONS" -rzvh --delete ./dist/ root@$DEPLOY_HOST:/var/www/$DEPLOY_FOLDER/
            ssh $SSH_OPTIONS root@$DEPLOY_HOST "service nginx restart"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_staging:
          context:
            - slack-secrets
          filters:
            branches:
              only:
                - main
      - build_and_deploy_mainnet:
          context:
            - slack-secrets
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
